### ISSUE TITLE
FDR values > 1

### ISSUE THREAD

**Issue by antonkratz** [mhk7/alignOntology#4]
Using `calculateFDRs`, in the resulting file `FDRs` I sometimes get FDR values (4th column) which are larger than one. Is this a bug? My understanding and expectation is that a FDR value should always be between 0 and 1. Could I have a comment on this? Thanks!

**Comment by mhk7** [comment]
Hi Anton,

Sorry about the slow response. This is not a bug just a result of the way
FDR is estimated which can sometimes give values a bit above 1 (which can
be thought of as ~=1). The FDR is an estimate of what fraction of terms
aligned between the reference ontology and constructed ontology at a
particular score were achieved by random chance. This is calculated by
creating several ontologies with identical structure to the constructed
ontology but with genes randomly assigned to terms. These random ontologies
are then aligned with the reference ontology to get alignment scores. Then
for each alignment between the reference and constructed ontologies (with
an alignment score S), the program counts the number of term alignments
with at least score S (let's call this Ts for True Alignments with score >=
S). It also counts the average number of term alignments with at least
score S in the randomly created ontologies (let's call this Rs). The FDR is
then Rs/Ts, with the idea that at a given score S by random chance we would
see Rs alignments but we are actually seeing Ts, so Rs/Ts of these
alignments are likely to have been achieved by random chance.

Since this is an estimate with randomness involved, there are sometimes
situations for low alignment scores where there are actually a few more
random alignments than true alignments with scores greater than a given
score S. This gives an FDR >1 by this estimate. Obviously that doesn't
really make any sense as you have noted but I never bothered to round that
back to 1 since in most cases any FDR anywhere close to that high is
indicative of a probably unimportant and easily discarded alignment. I
usually used FDR cutoffs of 0.05 of 0.1 in most situations.

Anyway, hope that is helpful. Let me know if you have any other questions
or if that explanation isn't clear.

Michael

**Comment by antonkratz** [comment]
Thank you Mike for this very clear and thorough explanation! I will close this issue.
